### PR TITLE
increase version, change defo release branch and add changelog

### PR DESCRIPTION
**Pull request by solegalli**

### CODE REVIEW

**Comment by solegalli** [comment]
Hello everybody,

@hectorpatino @AgustinFi @AndrewTanQB @bitsbuffer @indymnv @ashok49473 @ChristopherGS 

I aim to release a new version of Feature-engine with your contributions tomorrow. I don't know all of your names so in the changelog I added your github user.

Please check this file: https://github.com/solegalli/feature_engine/pull/270/files#diff-b4befaa2329c7b8dea845ded7b378238753e817e217236dedfad00737a106776
 
and let me know if you would like your names changed (or removed), or if you have any other suggestion. 

Also, if you want me to tag you in linkedin or twitter please let me know your handles.

Cheers
Sole

**Comment by AgustinFi** [comment]
Hi @solegalli 

My name is Agustin Firpo and my linkedin is https://www.linkedin.com/in/agustinfirpo/

Thanks :)

**Comment by indymnv** [comment]
Thank you @solegalli 

My name is ok!, and my profile on Linkedln is https://www.linkedin.com/in/indy-michael-navarro-vidal/

kind regards

**Comment by hectorpatino** [comment]
My name is ok, this is my [LinkedIn profile ](https://www.linkedin.com/in/hectorpatino-geodata/) and this my [Twitter profile](https://twitter.com/RoTeCol)

**Comment by bitsbuffer** [comment]
Hi Solegalli,

My name is Shubhmay Potdar (github user: bitsbuffer) and my linkedin is
https://www.linkedin.com/in/shubhmay

**Pull request merged**
