### PR TITLE
add type annotations and docstrings

### PR DESCRIPTION
**Pull request by Okroshiashvili**
Add new type annotations and docstrings, as well as fix some old docstrings to be consistent.

### CODE REVIEW

**Comment by solegalli** [comment]
Hi @Okroshiashvili 

before making more changes, it would be good to discuss the format of the docstrings. I like how it is done in the package imbalanced learn:
https://imbalanced-learn.readthedocs.io/en/stable/generated/imblearn.under_sampling.CondensedNearestNeighbour.html#

and here the source code:
https://github.com/scikit-learn-contrib/imbalanced-learn/blob/12b2e0d/imblearn/under_sampling/_prototype_selection/_condensed_nearest_neighbour.py#L27

But for some reason, if in feature engine we pass the attributes to the init docstring, and the methods as well. I did not manage to make them appear under the right headings (methods, attributes).

Does this work for you?

I see that here:
https://feature-engine.readthedocs.io/en/latest/vartransformers/BoxCoxTransformer.html

lambda_dict does not appear under attributes, not sure if the source code says it should or not.

Could you let me know ?

cheers
Sole

**Comment by solegalli** [comment]
see #167

**Comment by Okroshiashvili** [comment]
@solegalli  I've checked the links you provide and they seem to use Numpy style docstrings. I'm using Google style docstrings. To build docs properly, we need to enable Sphinx extension Napoleon and build docs with it. After that, I hope everything will be as expected. For more info check the following: https://www.sphinx-doc.org/en/master/usage/extensions/napoleon.html

We can discuss and agree with unified style for docstrings in the code base and then I will rewrite all docs in that style.

**Comment by solegalli** [comment]
@Okroshiashvili thanks for the link. That was new to me :)

Could we stick to Numpy style then? most of the docs are already with the underline and without indentation.

At the top of the dosctrings, could we include **explanation**, **params**, **attributes** and **methods**, plus **examples** if any? could we add the >>> to the code examples if they are not there already?

and then the docstrings for the methods themselves, with sections **args**, **raises**,  and **returns**?

Also, could we have the type_hint changes in one PR and the changes in the docstrings in a different PR? it is easier to review. 
And also, if we need changes, I think it makes the back and forth easier as well.

Thanks a lot!

**Comment by Okroshiashvili** [comment]
@solegalli Sure we can stick to the Numpy style docstrings. Even, we can use ```imbalanced-learn``` as a template to build better Docs for ```feature-engine```.

I will reference this thread in #167 and in #152 

I will start working on writing type hints and send one PR for that and one separate PR for docstrings. I will do my best to include everything you suggested.

Let this PR be open until I will do all the necessary preparation work and then I will close this PR.

It's better first to complete type annotations and then go for better Docs, as the latter requires more work. Hence, I will send new PR which will only include type annotations. After we finish writing type annotations then I will work on rewriting Docs.

If this sounds good, please confirm. :)

**Comment by solegalli** [comment]
@Okroshiashvili sounds great! thank you!

**Comment by Okroshiashvili** [comment]
closing this PR in favor of separate PR for type annotations

**Pull request closed without merging**
