### PR TITLE
expands function to accept variables cast as category 

### LINKED ISSUE #259: modify _find_or_check_categorical_variables to support dtype='category'
**Is your feature request related to a problem? Please describe.**
Currently, _find_or_check_categorical_variables in variable_manipulation.py only checks for type object to determine categorical variables.

**Describe the solution you'd like**
The method should be enhanced to support dtype="category" to support cases where user has used category datatype to optimise memory footprint of Pandas dataframe. 
(https://pandas.pydata.org/pandas-docs/stable/user_guide/categorical.html)

### PR DESCRIPTION
**Pull request by solegalli**
closes #259 
closes #260

### CODE REVIEW

**Comment by solegalli** [comment]
@bitsbuffer would you like to review this PR?

**Comment by bitsbuffer** [comment]
@solegalli sure, will do it asap.

**Review by bitsbuffer — COMMENTED** [review]
@solegalli The PR looks good to me.

**Comment by solegalli** [comment]
thank you! @bitsbuffer

**Pull request merged**
