### PR TITLE
Check for return_object is True in RareLabelEncoder

### PR DESCRIPTION
**Pull request by KarthikKothareddy**
As promised, pulled the test into a new branch and submitting this PR

### CODE REVIEW

**Comment by KarthikKothareddy** [comment]
@solegalli just to make sure that we're on the same page here. I'm posting the expected behavior for the below piece of snippet. 
`
import pandas as pd
from feature_engine.categorical_encoders import RareLabelCategoricalEncoder

df = pd.DataFrame({'var_A': ['B'] * 9 + ['A'] * 6 + ['C'] * 4 + ['D'] * 1,
      'var_B': ['A'] * 10 + ['B'] * 6 + ['C'] * 4,
      'target': ["255"] * 20})


rare_encoder = RareLabelCategoricalEncoder(n_categories=2, tol=0.1, return_object=True)
X = rare_encoder.fit_transform(df)
X.dtypes

var_A     object
var_B     object
target    object
dtype: object

`

**Comment by solegalli** [comment]
for this test, we need a dataframe where varA and varB are numerical, and not strings.

**Comment by solegalli** [comment]
df = pd.DataFrame({'var_A': ['100'] * 9 + ['50'] * 6 + ['10'] * 4 + ['8'] * 1,
'var_B': ['120'] * 10 + ['100'] * 6 + ['50'] * 4,
'target': ["255"] * 20})
case - dataframe with numerical variables as object, transformer returns numerical type (return_object=False)

rare_encoder = RareLabelCategoricalEncoder(
variables=["var_A", "var_B"], n_categories=2, tol=0.1, return_object=False
)
X = rare_encoder.fit_transform(df)
X.dtypes
expected output

var_A float or int
var_B float or int
target int64
dtype: object
case - dataframe with numerical variables as object, transformer returns object type (return_object=True)

rare_encoder = RareLabelCategoricalEncoder(
variables=["var_A", "var_B"], n_categories=2, tol=0.1, return_object=False
)
X = rare_encoder.fit_transform(df)
X.dtypes
expected output

var_A object
var_B object
target object
dtype: object

@KarthikKothareddy

**Comment by KarthikKothareddy** [comment]
@solegalli 

`df = pd.DataFrame({'var_A': ['100'] * 9 + ['50'] * 6 + ['10'] * 4 + ['8'] * 1,
'var_B': ['120'] * 10 + ['100'] * 6 + ['50'] * 4,
'target': ["255"] * 20})
# case - dataframe with numerical variables as object, transformer returns numerical type (return_object=False)

rare_encoder = RareLabelCategoricalEncoder(
variables=["var_A", "var_B"], n_categories=2, tol=0.1, return_object=False
)
X = rare_encoder.fit_transform(df)
X.dtypes`

The above code outputs the below for both **return_object = True** and **return_object = False**

`var_A     object
var_B     object
target    object
dtype: object`

**Comment by solegalli** [comment]
@KarthikKothareddy and if instead of '100' we create the variables with real numbers, then re-cast varA and varB as object, does it return object in both cases?
if yes, then I need to investigate this behaviour more, wonder there is a bug.

**Comment by KarthikKothareddy** [comment]
It still returns the same output even after explicitly casting the numeric to an object type.

**Pull request merged**
