### PR TITLE
Target mean selection closes #170

### PR DESCRIPTION
**Pull request by solegalli**

### CODE REVIEW

**Comment by solegalli** [comment]
@ttungl Hello again.

I have modified the selector as per the comments I made on the old PR. 

Would you be able to modify the test so that they fit this new selector?

Cheers
Sole

**Comment by ttungl** [comment]
> @ttungl Hello again.
> 
> I have modified the selector as per the comments I made on the old PR.
> 
> Would you be able to modify the test so that they fit this new selector?
> 
> Cheers
> Sole

Hi Sole, Thanks for your patience. I am almost done updating the changes you suggested. 
Yes, I will modify the test to fit the new selector. I will keep you posted. Thanks, Sole!

**Comment by solegalli** [comment]
> Hi Sole, Thanks for your patience. I am almost done updating the changes you suggested.
> Yes, I will modify the test to fit the new selector. I will keep you posted. Thanks, Sole!

Hi @ttungl , just in case I did not understand correctly. I already modified the selector, We need to work on the tests now, and the docs.

Regarding the selector, I think the only bit that needs checking is if the lines that capture the categorical and numerical variables are working as intended. Not sure they are,

Cheers

Sole

**Comment by solegalli** [comment]
Hey @ttungl

I worked a but more on the selection class, and now it is working as expected and I included 1 test that works fine.

We need to add the following tests:

1 test with a df that contains only categorical variables
1 test with a df that contains both numerical and categorical variables
1 test that evaluates the r2_score (can be included in one of the above 2)
1 tests for the errors
- when no y is passed
- when selector is not fitted
- when the parameters are not the allowed values (test every parameter)

the first 2 tests are the most important ones.

Would you have time to give me a hand with this? 

Thank you!

Sole

**Comment by ttungl** [comment]
> Hey @ttungl
> 
> I worked a bit more on the selection class, and now it is working as expected and I included 1 test that works fine.
> 
> We need to add the following tests:
> 
> 1 test with a df that contains only categorical variables
> 1 test with a df that contains both numerical and categorical variables
> 1 test that evaluates the r2_score (can be included in one of the above 2)
> 1 tests for the errors
> 
> * when no y is passed
> * when selector is not fitted
> * when the parameters are not the allowed values (test every parameter)
> 
> the first 2 tests are the most important ones.
> 
> Would you have time to give me a hand with this?
> 
> Thank you!
> 
> Sole

Hi Sole, I will take care of the test as suggested. I got some issue with the pipeline part, hopefully, I can figure out soon and implement the test cases. Thanks, Sole.
Best,
Tung

**Comment by solegalli** [comment]
TODO:

- how to handle NA introduced when categories or bins are rare
- example in the documentation

**Comment by ttungl** [comment]
Examples for ROC AUC score and R2 score:
+ [working] https://github.com/ttungl/feature_engine/blob/target-mean-encoding/examples/Examples_target_mean_selection_roc_auc_score_classification.ipynb
+ [currently debugging] https://github.com/ttungl/feature_engine/blob/target-mean-encoding/examples/Examples_target_mean_selection_r2_score_regression.ipynb

**Comment by solegalli** [comment]
Hi @ttungl

I've recently fixed a number of bugs to the select by target mean  class. I wonder whether your notebooks would run now? Would you have time to test it?

Cheers
Sole

**Comment by ttungl** [comment]
> Hi @ttungl
> 
> I've recently fixed a number of bugs to the select by target mean class. I wonder whether your notebooks would run now? Would you have time to test it?
> 
> Cheers
> Sole

Hi Sole,

Let me check the latest updated version of the target mean class and run the notebooks to test them and will keep you posted.  

Thanks, Sole!
Best,
Tung

**Comment by ttungl** [comment]
Hi Sole,

I just did a test for the target mean encoding class, it seems unlikely to work with the R2_score [2]. It works okay with ROC-AUC [1]. I posted the notebooks below for your review. Please let me know if you have any suggestions on the issue. Thanks, Sole!

[1] [roc-auc example notebook](https://github.com/ttungl/feature_engine/blob/master/examples/Examples_target_mean_selection_roc_auc_score_classification.ipynb)
[2] [r2-score example notebook](https://github.com/ttungl/feature_engine/blob/master/examples/Examples_target_mean_selection_r2_score_regression_feature_engine_v1.0.2.ipynb)

**Comment by solegalli** [comment]
Hi @ttungl 

I think the problem is that the categorical variables have too many categories or categories that are rare, and the numerical variables are too skewed. The selector that you are using will replace categorical variables by the target mean value per category. But if categories are rare, there might be categories in the test set not present in the train set, and those will be encoded as NaN.
The same happens with skewed numerical variables, if we sort those in say 5 bins but the variables are too skewed, they will end up having maybe 2 bins in the train set and then 3 bins in the test set, and the third bin will be encoded as NaN.

To resolve this issue, try decreasing the number of bins inside the selector, and grouping rare labels. See these notebooks as examples for the transformations:

https://github.com/solegalli/feature_engine/blob/master/examples/selection/Select-by-Target-Mean-Encoding.ipynb

https://www.kaggle.com/solegalli/predict-house-price-with-feature-engine

https://www.kaggle.com/solegalli/feature-engineering-and-model-stacking

Is this useful?

Cheers

**Pull request merged**
